import React from "react";
import Head from "next/head";

const Cart = () => {
  return (
    <>
      <Head>
        <title>Корзина || Towbars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Корзина</div>
    </>
  );
};

export default Cart;
